[build]
  command = "vite build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = []

  [functions.esbuild_config_override]
  loader = { ".js" = "jsx", ".mjs" = "jsx" }